version: "3.9"

services:
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/catalog
    depends_on:
      - db

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./worker
    depends_on:
      - redis

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    ports:
      - "8080:80"
    depends_on:
      - catalog-service
      - order-service

volumes:
  pg_data:
