apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: DATABASE_HOST

            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: DATABASE_PORT

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: DATABASE_NAME

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: DATABASE_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: DATABASE_PASSWORD


